# Grails
grailsVersion=6.2.3
grailsGradlePluginVersion=6.1.2
kintGradlePluginVersion=2.2.1
grailsSpringSecurityVersion=6.1.2
grailsMigrationPluginVersion=4.2.1
gormVersion=8.0.3
micronautJsonCoreVersion=3.10.8

# Plugins
viewsGradleVersion=3.1.2

# Deps
minioVersion=8.6.0
kafkaVersion=3.9.2
postgresVersion=42.7.11
hikariVersion=5.1.0
# We really need to retire this library asap
httpBuilderVersion=1.0.4
# TODO does liquibase 5 work with our grails modules?
liquibaseVersion=4.33.0
h2Version=2.1.212
janinoVersion=3.1.9
icu4jVersion=62.1
okHttpVersion=4.12.0
kotlinStdLibVersion=1.8.10
awsS3JavaSDKVersion=1.12.770
antlrVersion=4.7
# This situation with logback is really quite unfortunate
# Fixable in spring boot v3 and beyond hopefully
logbackCompileVersion=1.5.34
logbackRuntimeVersion=1.2.13
#logbackVersion=1.5.33

# Transitive deps
springSecurityCoreVersion=6.5.11
springSecurityVersion=5.8.16
bouncyCastleVersion=1.84
glassfishJakartaElVersion=3.0.4
glassfishJakartaElApiVersion=3.0.3
commonsFileUploadVersion=1.6.0
nettyBOMVersion=4.1.135.Final
undertowVersion=2.2.39.Final
jacksonVersion=2.18.7

version=0.1
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
