// Not sure if this is strictly necessary at this stage
pluginManagement {
    repositories {
        maven { url = "https://nexus.k-int.com/repository/build-tooling/" }
        maven { url = "https://nexus.k-int.com/repository/releases/" }
        mavenLocal()
        maven {
            url = "https://repo.grails.org/grails/core/"
            mavenContent { releasesOnly() }
        }
        gradlePluginPortal()
    }
    plugins {
    }
}

rootProject.name = "web-toolkit-ce"
